# **Online Retail, Practice Piece**

## Objectives

* Practice the process of cleaning and investigating data. This is the ETL notebook.


## Inputs

* Dataset 
* Libraries required for analysis 

## Outputs

* A cleaned/adapted dataset for Exploratiry Data Analysis

## Additional Comments

* AI is being used to as a teaching tool to help provide practice and development
and it's use will be disclosed as is.

---

# Change working directory

*The notebooks are stored in subfolders, make sure the follwoing commands are run first per each kernal load. 
Otherwise the notebook will not function correctly.

* Changing the working directory from its current folder to its parent folder
* Access the current directory with os.getcwd()

In [1]:
import os
current_dir = os.getcwd()
current_dir

'c:\\Users\\NateM\\Documents\\vcsode-projects\\PostGradPractice1\\jupyter_notebooks'

Need to make the parent of the current directory the new current directory
* os.path.dirname() gets the parent directory
* os.chir() defines the new current directory

In [2]:
os.chdir(os.path.dirname(current_dir))
print("You set a new current directory")

You set a new current directory

Confirm the new current directory

In [3]:
current_dir = os.getcwd()
current_dir

'c:\\Users\\NateM\\Documents\\vcsode-projects\\PostGradPractice1'

# Import BLock

Libraires needed

In [4]:
# Tools for the trade
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

---

# Section 1 - Extraction

In [7]:
# Opening the dataset into a pandas dataframe and storing
# it into a variable
df_raw = pd.read_excel("Dataset/Raw/OnlineRetail.xlsx")

# Calling the variable to check it's loaded right
df_raw.head(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

Now that the dataset is loaded it can receive inital inspection checks.

In [ ]:
# Get a statistical summary of the numerical columns
df_raw.describe()

,Quantity,InvoiceDate,UnitPrice,CustomerID
count,541909.000000,541909,541909.000000,406829.000000
mean,9.552250,2011-07-04 13:34:57.156386048,4.611114,15287.690570
min,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000
25%,1.000000,2011-03-28 11:34:00,1.250000,13953.000000
50%,3.000000,2011-07-19 17:17:00,2.080000,15152.000000
75%,10.000000,2011-10-19 11:27:00,4.130000,16791.000000
max,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000
std,218.081158,NaN,96.759853,1713.600303

An immediate jump out is the minimum Quantity value of -80,955.0 and a minimum UnitPrice of -11062.06. CustomerID isn't going to show us much here, as it's numerical content doesn't mean anything in what we're looking for. Invoice date intially seems like it has some wonky values but that's due to the type of information it is against the aggregation method placed on it.

---

---